### ISSUE TITLE
The intro video starts showing some seconds later

### ISSUE THREAD

**Issue by JuanObiJuan** [JuanObiJuan/videocontroller#11]
I can not see the animation from the first text, the video is jumping from the last frame to maybe one second from the beginning  and not from 0. If there is no way to solve that i can make a intro video that takes more time to show the first animation.

**Comment by Dickby** [comment]
This might be a real problem, i tried to fix that but it even happens if you start vlc from the command line

**Comment by JuanObiJuan** [comment]
So then the solution is create anew video with more time at the beginning before the animation. Thanks for trying.

**Comment by Dickby** [comment]
I found another dirty workaround for this, but it's really ugly.
But if your client wants to change the introvideo, it would be nice if it's just working by itself.

**Comment by JuanObiJuan** [comment]
It works! Thanks.
