### ISSUE TITLE
Be prepared to simulate a pulse

### ISSUE THREAD

**Issue by JuanObiJuan** [JuanObiJuan/videocontroller#12]
The Bluetooth light system switches are here and Im integrating this circuit in the board. On the manual they say this is ready for push buttons. This means that maybe we will need to simulate a  pulse (on during some milliseconds and the off)) instead a switch all the time on /off when the status for the player is changing. Maybe we will not need this feature but if we need I only can realize a bit late when Im already there in the installation testing the light system

**Comment by Dickby** [comment]
There is an option now to pulse by setting pulseRelay to True

**Comment by JuanObiJuan** [comment]
It works! I changed the relais signal a bit to match normally open switch beahviour.
