### ISSUE TITLE
Relais state

### ISSUE THREAD

**Issue by JuanObiJuan** [JuanObiJuan/videocontroller#4]
When the user is in front of the screen and the main video ends, its starting again as it shlud be but the relais update the state for a very short because setRelaisIntroVideo is called and after that setRelaisMainVideo is called again, this means the lights in the room are going to have a strange behaviour. Ideally if the user is in from of the screen and the main video is in a loop the light status in the room is never updated.

**Comment by Dickby** [comment]
This could be fixed now, but i'm not shure

**Comment by JuanObiJuan** [comment]
I have to try later but just to check whats going on you could change your led connection (the cable not the led definition) in the pi for the gpio 17 or 27 instead of 4

**Comment by Dickby** [comment]
It changes the relays only if the video is changed (at least with the light it works).
If you can confirm this we can close this issue

**Comment by JuanObiJuan** [comment]
It works awesome!
