### ISSUE TITLE
small bug at the end of the main video when is played at least two times

### ISSUE THREAD

**Issue by JuanObiJuan** [JuanObiJuan/videocontroller#5]
If the user is in front of the screen at the end of the mainvideo, the main video plays again, right after that if the user leaves the position, when the video ends, the player reproduce once more the main video instead the loop.

**Comment by JuanObiJuan** [comment]
update: The main video is always played two times

**Comment by JuanObiJuan** [comment]
another update: not always... so something is weird here

**Comment by Dickby** [comment]
Shouldn't be like that anymore please test.

**Comment by JuanObiJuan** [comment]
It works!
