### ISSUE TITLE
sensor not responding

### ISSUE THREAD

**Issue by JuanObiJuan** [JuanObiJuan/videocontroller#6]
Sometimes the sensor is not responding after the intialization, mus.py stay waiting after loging:
[...]
ProductRevisionMajor : 1
ProductRevisionMinor:15

and is waiting there forever

I think maybe is the way that I interrupt the python script to run it again, but even killing the thread the only way to recover the communication with the sensor is rebooting the pi or disconnecting the sensor phisically from the the connector. 

It would be awesome a way to force a reset in the sensor at the beginning if this possibility exist

**Comment by Dickby** [comment]
I can't really reproduce this problem, if i remember correctly this happened to me once at the beginning, but i tried now lots of times and it doesn't happen.

**Comment by Dickby** [comment]
the "open" funciton of the sensor has a optional argument "reset" which is False by default. If you can reproduce the problem, we could test if this fixes it.

**Comment by Dickby** [comment]
I set the default argument "reset" this might have fixed it.

**Comment by JuanObiJuan** [comment]
I was trying a bit and it looks that this never happen again. It works!
