### ISSUE TITLE
No internet access

### ISSUE THREAD

**Issue by JuanObiJuan** [JuanObiJuan/videocontroller#9]
When the script is loaded form the autostart still there is no wify connection . The script should wait some time before checking the connectivity

**Comment by Dickby** [comment]
It is now waiting for a given time and checking the wifi connection.
If after "timeToWaitForWifi" seconds there is still no wifi connection, it procedes without.

**Comment by JuanObiJuan** [comment]
it doesnt matter the amount of time i put its never waiting

**Comment by JuanObiJuan** [comment]
I had to modify the script and now its working. I also add the feature to pull from this repo so its updating the python scripts but not the config.json. For this tehre is a new dependency described in the wiki.
